In [12]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 
import re
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split

In [27]:
data = pd.read_json("News_Category_Dataset_v3.json",lines=True)

In [3]:
data

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [28]:
def mapping_to_10(cat):
    if cat not in ["POLITICS","WELLNESS","ENTERTAINMENT","TRAVEL","STYLE & BEAUTY","QUEER VOICES","FOOD & DRINK","BUSINESS","SPORTS"]:
        return "OTHER"
    else:
        return cat

In [29]:
data['category_10']=data['category'].apply(mapping_to_10)
data

,link,headline,category,short_description,authors,date,category_10
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23,OTHER
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23,OTHER
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23,OTHER
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23,OTHER
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22,OTHER
...,...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28,OTHER
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28,SPORTS
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28,SPORTS
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28,SPORTS
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28,SPORTS

In [30]:
data = data[["headline", "category_10"]].copy()
data.dropna(inplace=True)

In [31]:
data

                                                 headline category_10
0       Over 4 Million Americans Roll Up Sleeves For O...       OTHER
1       American Airlines Flyer Charged, Banned For Li...       OTHER
2       23 Of The Funniest Tweets About Cats And Dogs ...       OTHER
3       The Funniest Tweets From Parents This Week (Se...       OTHER
4       Woman Who Called Cops On Black Bird-Watcher Lo...       OTHER
...                                                   ...         ...
209522  RIM CEO Thorsten Heins' 'Significant' Plans Fo...       OTHER
209523  Maria Sharapova Stunned By Victoria Azarenka I...      SPORTS
209524  Giants Over Patriots, Jets Over Colts Among  M...      SPORTS
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...      SPORTS
209526  Dwight Howard Rips Teammates After Magic Loss ...      SPORTS

[209527 rows x 2 columns]

In [32]:
def preprocess_headline(text):
    text = text.lower()
    text = re.sub(r"\d+", "<NUM>", text)
    
    text = re.sub(r"[^\w\s<>]", "", text)
    
    tokens = word_tokenize(text)
    
    return tokens

In [33]:
data["tokens"] = data["headline"].apply(preprocess_headline)

In [35]:
X = data["tokens"]
y = data["category_10"]

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [36]:
train_df = pd.DataFrame({"tokens": x_train,"category_10": y_train})
test_df = pd.DataFrame({"tokens": x_test,"category_10": y_test})

In [37]:
print(train_df["category_10"].value_counts())

category_10
OTHER             76118
POLITICS          28481
WELLNESS          14356
ENTERTAINMENT     13889
TRAVEL             7920
STYLE & BEAUTY     7851
QUEER VOICES       5078
FOOD & DRINK       5072
BUSINESS           4794
SPORTS             4062
Name: count, dtype: int64

In [ ]:
train_df.to_csv("train_df.csv", index=False)
test_df.to_csv("test_df.csv", index=False)